# config/config.yaml
trading:
  exchanges:
    - binance
    - kraken
    - coinbase
  symbol: BTC/USDT
  timeframe: 1h
  amount: 0.001
  testnet: true
  fees:
    taker: 0.001
    maker: 0.0005
  risk:
    conservative:
      max_position_size: 0.005
      max_daily_loss: 0.02
      stop_loss: 0.02
      take_profit: 0.05
      max_leverage: 1.0
    moderate:
      max_position_size: 0.01
      max_daily_loss: 0.05
      stop_loss: 0.05
      take_profit: 0.10
      max_leverage: 2.0
    aggressive:
      max_position_size: 0.02
      max_daily_loss: 0.10
      stop_loss: 0.10
      take_profit: 0.15
      max_leverage: 3.0
  strategies:
    breakout:
      atr_period: 14
      breakout_threshold: 2.0
    mean_reversion:
      rsi_upper: 70
      rsi_lower: 30
  pair_selection:
    min_volume: 1000000
    min_volatility: 0.02
    max_spread: 0.001
    min_liquidity: 100000

ml:
  model_path: ml/model.pkl
  features:
    - sma_20
    - sma_50
    - rsi_14
    - bollinger_upper
    - bollinger_lower
    - macd
    - sentiment_score
    - whale_ratio
  train_interval: 86400
  batch_size: 1000
  historical_data_years: 20

rl:
  model_path: ml/rl_model.h5
  episodes: 1000
  gamma: 0.95
  epsilon: 1.0
  epsilon_decay: 0.995
  learning_rate: 0.001
  batch_size: 64

database:
  url: sqlite:///local_trading.db

sentiment:
  api_key: your_cryptopanic_api_key
  sources:
    - cryptopanic
    - x

social:
  tradingview_api_key: your_tradingview_api_key

onchain:
  glassnode_api_key: your_glassnode_api_key
