# config/config.yaml
trading:
  exchange: binance
  symbol: BTC/USDT
  timeframe: 1h
  amount: 0.001
  testnet: true
  fees:
    taker: 0.001  # 0.1% taker fee
    maker: 0.0005  # 0.05% maker fee
  risk:
    conservative:
      max_position_size: 0.005  # 0.5% of portfolio
      max_daily_loss: 0.02    # 2% daily loss
      stop_loss: 0.02         # 2% stop-loss
      take_profit: 0.05       # 5% take-profit
    moderate:
      max_position_size: 0.01   # 1% of portfolio
      max_daily_loss: 0.05     # 5% daily loss
      stop_loss: 0.05          # 5% stop-loss
      take_profit: 0.10        # 10% take-profit
    aggressive:
      max_position_size: 0.02   # 2% of portfolio
      max_daily_loss: 0.10     # 10% daily loss
      stop_loss: 0.10          # 10% stop-loss
      take_profit: 0.15        # 15% take-profit
  strategies:
    breakout:
      atr_period: 14
      breakout_threshold: 2.0
    mean_reversion:
      rsi_upper: 70
      rsi_lower: 30
  pair_selection:
    min_volume: 1000000  # Minimum 24h volume in USD
    min_volatility: 0.02  # Minimum daily volatility
    max_spread: 0.001     # Maximum bid-ask spread

ml:
  model_path: ml/model.pkl
  features:
    - sma_20
    - sma_50
    - rsi_14
    - bollinger_upper
    - bollinger_lower
    - macd
    - sentiment_score
  train_interval: 86400  # Retrain every 24 hours
  batch_size: 1000
  historical_data_years: 20

rl:
  model_path: ml/rl_model.h5
  episodes: 1000
  gamma: 0.95
  epsilon: 1.0
  epsilon_decay: 0.995
  learning_rate: 0.001
  batch_size: 64

database:
  url: sqlite:///local_trading.db

sentiment:
  api_key: your_cryptopanic_api_key
  sources:
    - cryptopanic
    - x
