# Arasaka Neural-Net Trading Matrix Configuration
# Customize these settings to optimize your trading strategy

trading:
  # Supported exchanges
  exchanges:
    - binance
    # - kraken  # Uncomment to enable
    # - coinbase  # Uncomment to enable
  
  # Default trading pair
  symbol: BTC/USDT
  
  # Timeframe for analysis (1m, 5m, 15m, 30m, 1h, 4h, 1d)
  timeframe: 1h
  
  # Default trade amount (in base currency)
  amount: 0.001
  
  # Start in testnet mode
  testnet: true
  
  # Trading fees
  fees:
    taker: 0.001  # 0.1%
    maker: 0.0005  # 0.05%
  
  # Risk profiles
  risk:
    default:
      max_leverage: 3.0
    
    conservative:
      max_position_size: 0.005  # 0.5% of portfolio
      max_daily_loss: 0.02      # 2% daily loss limit
      stop_loss: 0.02           # 2% stop loss
      take_profit: 0.05         # 5% take profit
      max_leverage: 1.0         # No leverage
    
    moderate:
      max_position_size: 0.01   # 1% of portfolio
      max_daily_loss: 0.05      # 5% daily loss limit
      stop_loss: 0.05           # 5% stop loss
      take_profit: 0.10         # 10% take profit
      max_leverage: 2.0         # 2x leverage
    
    aggressive:
      max_position_size: 0.02   # 2% of portfolio
      max_daily_loss: 0.10      # 10% daily loss limit
      stop_loss: 0.10           # 10% stop loss
      take_profit: 0.15         # 15% take profit
      max_leverage: 3.0         # 3x leverage
  
  # Trading strategies configuration
  strategies:
    breakout:
      atr_period: 14
      breakout_threshold: 2.0
      volume_multiplier: 1.5
    
    mean_reversion:
      rsi_upper: 70
      rsi_lower: 30
      bollinger_period: 20
      bollinger_std: 2.0
    
    momentum:
      macd_fast: 12
      macd_slow: 26
      macd_signal: 9
      trend_strength: 0.02
    
    scalping:
      min_profit: 0.002  # 0.2% minimum profit
      max_hold_time: 300  # 5 minutes max hold
    
    swing:
      trend_period: 50
      entry_confirmation: 3  # Number of confirming signals
  
  # Pair selection criteria
  pair_selection:
    min_volume: 1000000       # $1M minimum daily volume
    min_volatility: 0.02      # 2% minimum daily volatility
    max_spread: 0.001         # 0.1% maximum spread
    min_liquidity: 100000     # $100k minimum order book liquidity
    volume_spike_threshold: 0.5  # 50% volume increase threshold

# Machine Learning Configuration
ml:
  model_path: ml/model.pkl
  
  # Features for ML model
  features:
    - sma_20              # 20-period Simple Moving Average
    - sma_50              # 50-period Simple Moving Average
    - rsi_14              # 14-period RSI
    - bollinger_upper     # Upper Bollinger Band
    - bollinger_lower     # Lower Bollinger Band
    - macd                # MACD line
    - sentiment_score     # Social sentiment score
    - whale_ratio         # Whale activity ratio
  
  # Training parameters
  train_interval: 86400   # Retrain every 24 hours
  batch_size: 1000        # Training batch size
  historical_data_years: 15  # Years of data to use
  
  # Model hyperparameters
  xgboost:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    subsample: 0.8
    colsample_bytree: 0.8

# Reinforcement Learning Configuration
rl:
  model_path: ml/rl_model.h5
  
  # Training parameters
  episodes: 100           # Reduced for faster training
  gamma: 0.95             # Discount factor
  epsilon: 1.0            # Initial exploration rate
  epsilon_decay: 0.995    # Exploration decay
  epsilon_min: 0.01       # Minimum exploration
  learning_rate: 0.001    # Neural network learning rate
  batch_size: 64          # Experience replay batch size
  
  # DQN Architecture
  layers:
    - 128  # First hidden layer
    - 64   # Second hidden layer
    - 32   # Third hidden layer
  
  dropout: 0.2            # Dropout rate
  activation: relu        # Activation function

# Sentiment Analysis Configuration
sentiment:
  # API key in .env file
  sources:
    - cryptopanic
    - x  # Twitter/X
  
  # Sentiment weights
  weights:
    x: 0.6
    cryptopanic: 0.4
  
  # Keywords for analysis
  bullish_keywords:
    - bull
    - moon
    - pump
    - long
    - buy
    - breakout
    - ATH
  
  bearish_keywords:
    - bear
    - dump
    - crash
    - short
    - sell
    - breakdown
    - rekt

# Social Signal Configuration
social:
  # TradingView integration
  min_rating: 4.0         # Minimum signal rating
  
  # Social metrics
  min_followers: 1000     # Minimum follower count
  sentiment_threshold: 0.6  # Minimum sentiment score

# On-chain Analysis Configuration
onchain:
  # Glassnode metrics
  metrics:
    - exchange_inflow
    - exchange_outflow
    - whale_transactions
    - active_addresses
  
  # Thresholds
  whale_threshold: 100    # BTC
  inflow_alert: 1000      # BTC daily inflow

# Database Configuration
database:
  url: sqlite:///local_trading.db
  
  # Backup settings
  backup_interval: 86400  # Daily backups
  backup_retention: 7     # Keep 7 days of backups

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Log rotation
  max_bytes: 10485760     # 10MB
  backup_count: 5

# API Configuration
api:
  # Rate limits
  rate_limit:
    requests_per_minute: 60
    requests_per_hour: 1000
  
  # Timeout settings
  timeout: 30             # API request timeout in seconds
  
  # CORS settings
  cors_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"

# Notification Settings (Future Feature)
notifications:
  enabled: false
  
  # Notification triggers
  triggers:
    large_profit: 0.05    # 5% profit
    large_loss: -0.05     # 5% loss
    error_count: 5        # System errors
  
  # Channels
  channels:
    - log  # Default to log file

# Performance Optimization
optimization:
  # Caching
  cache_ttl: 300          # 5 minutes cache
  
  # Parallel processing
  max_workers: 4          # Thread pool size
  
  # GPU settings
  use_gpu: true           # Enable GPU for ML/RL
  gpu_memory_limit: 2048  # MB
