# config/config.yaml
trading:
  exchange: binance
  symbol: BTC/USDT
  timeframe: 1h
  amount: 0.001
  testnet: true
  risk:
    max_position_size: 0.01  # Max 1% of portfolio per trade
    max_daily_loss: 0.05  # Max 5% daily loss

ml:
  model_path: ml/model.pkl
  features:
    - sma_20
    - sma_50
    - rsi_14
  train_interval: 86400  # Retrain every 24 hours
  batch_size: 1000

database:
  url: sqlite:///local_trading.db
